# print(5>4)
# print(type(5>4))
# print("aab">"ab")
# print(type("aab">"ab"))
# print(type("False"))
# print("False"==False)
# print("ab"=="ab")
# print(5>4 and 4>9)
# print(not 4>9)
# print(True or False)
# print(True or True)
# print(type( True or True))
# print(5>4>3)
text="hello world"
print(text)
print(text[0:])
# print(text[:1])
